export const themes = {
  default: require('./custom-theme.json'),
  // black: require('./custom-theme-black.json'),
  // blackLight: require('./custom-theme-black-light.json'),
  // skyBlue: require('./custom-theme-blue.json'),
  // blue: require('./custom-theme-blue2.json'),
  // purple: require('./custom-theme-purple.json'),
  // teakBlue: require('./custom-theme-teak-blue.json'),
  nord0: require('./nord0.json'),
  // nord1: require('./nord1.json'),
  // nord2: require('./nord2.json'),
  nord3: require('./nord3.json'),
  // nord4: require('./nord4.json'),
  // nord5: require('./nord5.json'),
  // nord6: require('./nord6.json'),
  // nord7: require('./nord7.json'),
  nord8: require('./nord8.json'),
  // nord9: require('./nord9.json'),
  nord10: require('./nord10.json'),
  // nord11: require('./nord11.json'),
  nord12: require('./nord12.json'),
  // nord13: require('./nord13.json'),
  // nord14: require('./nord14.json'),
}
